import { Transaction } from "./types";

export const transactions: Transaction[] = [
  {
    id: "1",
    label: "Card declined at",
    name: "Netflix",
    amount: "-$8.79",
    date: "2024-09-01",
    week: "Week 1",
    status: "declined",
  },
  {
    id: "2",
    label: "Received from ",
    name: "Daniel Agoziem",
    amount: "+₦35,000",
    date: "2024-09-01",
    week: "Week 1",
    status: "received",
  },
  {
    id: "3",
    label: "Sent to ",
    amount: "-₦40,000",
    date: "2024-09-01",
    week: "Week 1",
    status: "sent",
    name: "@chinonsogreat",
  },
  {
    id: "4",
    label: "Sent to ",
    amount: "-₦8,000",
    date: "2024-09-01",
    week: "Week 1",
    status: "sent",
    name: "Oluwatobi Oseni",
  },
  {
    id: "5",
    label: "Reversal for",
    amount: "+₦31,950",
    date: "2024-09-01",
    week: "Week 1",
    status: "reversal",
    name: "Temidayo Anifowos",
  },
  {
    id: "6",
    label: "Balance Top up for ",
    amount: "+(₵80,000)",
    date: "2024-09-01",
    week: "Week 1",
    status: "topup",
    name: "Ghanian Cedi",
  },
  {
    id: "7",
    label: "Received from ",
    amount: "+₦6,900",
    date: "2023-07-01",
    week: "Week 2",
    status: "received",
    name: "@moneymade$$",
  },
  {
    id: "8",
    label: "Spent on ",
    amount: "-$50.09",
    date: "2023-07-01",
    week: "Week 2",
    status: "card",
    name: "NETFLIX.COM",
  },
];
