name: Run Tests

on:
  push:
    branches:
      - "main"
    pull_requests:
      branches:
        - "main"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/checkout@v2
        with:
          node-version: 20.10.0
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
